---
title: "Bihar Elections"
author: "Vijayvithal"
date: "10 November 2015"
output: html_document
---

```{r setup ,include=FALSE}

require(knitr)
knitr::opts_chunk$set(fig.width=12, fig.height=8, fig.path='Figs/',
                      echo=FALSE, warning=FALSE, message=FALSE)
opts_knit$set(root.dir = normalizePath('../'))

# Libraries
library(dplyr)
library(tidyr)
library(ggplot2)
library(scales)
library(dplyr)
library(tidyr)
library(ggplot2)
library(RCurl)
library(XML)
library(xml2)
library(lubridate)
library(xtable)
bihar<-data.frame()
```
```{r}
for(ac in 1:243) { #
url<-paste0("http://eciresults.nic.in/ConstituencywiseS04",ac,".htm",collapse = "")
if(!dir.exists("RawData/Bihar/")){
  dir.create("RawData/Bihar/")
}
 localfile<-paste0("RawData/Bihar/",ac,".htm",collapse="")
 if(!file.exists(localfile)){
 download.file(url,localfile)
   
 }
}
for(ac in 1:243) { #
 x<-read_html(localfile)
 constituency<-xml_text(xml_find_all(x,'//*[@id="div1"]/table[1]/tr[1]'))
 y<-htmlParse(localfile)
 table_node<-getNodeSet(y,'//*[@id="div1"]/table[1]')
 table<-readHTMLTable(table_node[[1]],skip.rows = 1:2,header = T)%>%mutate(constituency=constituency)
 bihar<-rbind(bihar,table)
}
print (getwd())

```
```{r}

bihar_tidy<-bihar%>%extract(constituency,c("constituency","Reservation"),regex='([^(]*)([(].*[)])?')%>%mutate(Reservation=gsub('[()]','',Reservation),constituency=gsub("Bihar -",'',constituency))
```